#!/bin/bash
npm i -D @babel/core
npm i -D @babel/preset-env
npm i -D @babel/preset-react
npm i -D autoprefixer
npm i -D babel-loader
npm i -D clean-webpack-plugin
npm i -D css-loader
npm i -D cssnano
npm i -D eslint
npm i -D file-loader
npm i -D html-loader
npm i -D html-webpack-plugin
npm i -D mini-css-extract-plugin
npm i -D node-sass
npm i -D postcss
npm i -D postcss-loader
npm i -D sass-loader
npm i -D style-loader
npm i -D webpack
npm i -D webpack-cli
npm i -D webpack-dev-server
npm i -D webpack-merge
npm i -D uuid
npm i --save bootstrap
npm i --save prop-types
npm i --save react
npm i --save react-dom
npm i --save react-redux
npm i --save react-router-dom
npm i --save reactstrap
npm i --save redux